# Generated by Django 5.2.6 on 2025-10-15 00:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('vigencia_dias', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documento_tipo',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('PERSONAL', 'Personal/Consumo'), ('VEHICULAR', 'Vehicular'), ('HIPOTECARIO', 'Hipotecario'), ('PYME', 'Micro/Pequeña Empresa')], max_length=20)),
                ('tasa_nominal_anual_min', models.DecimalField(decimal_places=4, max_digits=7)),
                ('tasa_nominal_anual_max', models.DecimalField(decimal_places=4, max_digits=7)),
                ('plazo_min', models.PositiveIntegerField()),
                ('plazo_max', models.PositiveIntegerField()),
                ('monto_min', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_max', models.DecimalField(decimal_places=2, max_digits=14)),
                ('metodo_amortizacion_default', models.CharField(default='frances', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'producto_financiero',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CI', 'Cédula de Identidad'), ('PAS', 'Pasaporte'), ('NIT', 'NIT')], default='CI', max_length=3)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100)),
                ('ingresos_mensuales', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('puntuacion_crediticia', models.IntegerField(default=0)),
                ('es_cliente_preferencial', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(default='73023A6D6D', max_length=10, unique=True)),
                ('departamento', models.CharField(choices=[('CREDITO', 'Crédito'), ('ADMIN', 'Administración'), ('TESORERIA', 'Tesorería'), ('ATENCION', 'Atención al Cliente')], max_length=20)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_supervisor', models.BooleanField(default=False)),
                ('puede_aprobar_creditos', models.BooleanField(default=False)),
                ('limite_aprobacion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('plazo_meses', models.PositiveIntegerField()),
                ('tasa_nominal_anual', models.DecimalField(decimal_places=4, max_digits=7)),
                ('moneda', models.CharField(default='BOB', max_length=10)),
                ('estado', models.CharField(choices=[('DRAFT', 'Borrador'), ('ENVIADA', 'Enviada'), ('EVALUADA', 'Evaluada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='ENVIADA', max_length=10)),
                ('tipo_credito', models.CharField(choices=[('PERSONAL', 'Personal'), ('VEHICULAR', 'Vehicular'), ('HIPOTECARIO', 'Hipotecario'), ('PYME', 'Micro/Pequeña Empresa')], default='PERSONAL', max_length=20)),
                ('tipo_trabajador', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado'), ('INDEPENDIENTE', 'Independiente')], default='PRIVADO', max_length=20)),
                ('score_riesgo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observacion_evaluacion', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='api.cliente')),
                ('oficial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='api.empleado')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.productofinanciero')),
            ],
            options={
                'db_table': 'solicitudes_credito',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metodo', models.CharField(default='frances', max_length=20)),
                ('moneda', models.CharField(default='BOB', max_length=10)),
                ('primera_cuota_fecha', models.DateField()),
                ('total_capital', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_interes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_cuotas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('redondeo_ajuste_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(db_column='solicitud_id', on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='api.solicitudcredito')),
            ],
            options={
                'db_table': 'plan_pago',
            },
        ),
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='solicitudes/%Y/%m/')),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('valido', models.BooleanField(default=None, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('documento_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.documentotipo')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='api.solicitudcredito')),
            ],
            options={
                'db_table': 'documento_adjunto',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanCuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nro_cuenta', models.IntegerField(default=0)),
                ('nro_cuota', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('capital', models.DecimalField(decimal_places=2, max_digits=16)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=16)),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=16)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ajuste_redondeo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='api.planpago')),
            ],
            options={
                'db_table': 'plan_cuota',
                'ordering': ['nro_cuota'],
                'unique_together': {('plan', 'nro_cuota')},
            },
        ),
        migrations.CreateModel(
            name='RequisitoProductoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trabajador', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado'), ('INDEPENDIENTE', 'Independiente')], max_length=20)),
                ('obligatorio', models.BooleanField(default=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.documentotipo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='api.productofinanciero')),
            ],
            options={
                'db_table': 'req_prod_doc',
                'unique_together': {('producto', 'tipo_trabajador', 'documento')},
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
            ],
            options={
                'unique_together': {('rol', 'permiso')},
            },
        ),
    ]
