# Generated by Django 5.2.6 on 2025-10-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='codigo_empleado',
            field=models.CharField(default='C0DF21D870', max_length=10, unique=True),
        ),
    ]
