# Generated by Django 5.2.6 on 2025-10-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_empleado_codigo_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='codigo_empleado',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
