# Generated by Django 5.2.6 on 2025-10-20 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_empleado_codigo_empleado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoValidacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_global', models.FloatField()),
                ('recomendacion', models.CharField(max_length=50)),
                ('factores_riesgo', models.JSONField(default=list)),
                ('confianza_modelo', models.FloatField()),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('metadata_modelo', models.JSONField(default=dict)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_ia', to='api.solicitudcredito')),
            ],
            options={
                'db_table': 'resultado_validacion_ia',
            },
        ),
        migrations.CreateModel(
            name='ValidacionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('OBSERVADO', 'Observado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('score_confianza', models.FloatField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('campos_extraidos', models.JSONField(default=dict)),
                ('fecha_validacion', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='api.documentoadjunto')),
                ('validado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'validacion_documento',
            },
        ),
    ]
