# Generated by Django 5.2.6 on 2025-10-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_resultadovalidacionia_validaciondocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadovalidacionia',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
