# Generated by Django 5.2.6 on 2025-10-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_resultadovalidacionia_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadovalidacionia',
            name='factores_positivos',
            field=models.JSONField(default=list),
        ),
    ]
