# Generated by Django 5.2.6 on 2025-10-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_resultadovalidacionia_factores_positivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadovalidacionia',
            name='detalles_analisis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
