# Generated by Django 5.2.6 on 2025-10-21 01:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_resultadovalidacionia_detalles_analisis'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancuota',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='plancuota',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TransaccionPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido'), ('REVERTIDO', 'Revertido')], default='PENDIENTE', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_client_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_autorizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('metodo_pago', models.CharField(default='TARJETA_CREDITO', max_length=50)),
                ('datos_pago', models.JSONField(blank=True, default=dict)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='api.plancuota')),
            ],
            options={
                'db_table': 'transaccion_pago',
                'ordering': ['-fecha_transaccion'],
            },
        ),
    ]
