# Generated by Django 5.2.7 on 2025-10-19 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('ACCESO', 'ACCESO'), ('CERRAR_SESION', 'CERRAR SESIÓN'), ('CREAR', 'CREAR'), ('ACTUALIZAR', 'ACTUALIZAR'), ('BORRAR', 'ELIMINAR')], max_length=20)),
                ('ruta', models.CharField(max_length=512)),
                ('metodo', models.CharField(max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('estado_http', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bitacora_eventos_v2',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['creado_en'], name='bitacora_ev_creado__048e1c_idx'), models.Index(fields=['accion'], name='bitacora_ev_accion_99fb70_idx'), models.Index(fields=['ruta'], name='bitacora_ev_ruta_177931_idx'), models.Index(fields=['metodo'], name='bitacora_ev_metodo_53e5b2_idx')],
            },
        ),
    ]
